# 1. Environment & Session
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# 2. Authentication Agent
exec-once = systemctl --user start hyprpolkitagent

# 3. Core Desktop Services
exec-once = hyprpaper                   # Wallpaper
exec-once = hypridle                    # Auto sleep
exec-once = nm-applet --indicator       # Network icon
exec-once = blueman-applet              # Bluetooth
exec-once = mako #Notification

# 4. Apps & Scripts
exec-once = elephant                    # Walker
exec-once = walker --gapplication-service
# 5. Your Scripts
exec-once = ~/.config/hypr/scripts/clip-limit.sh  #Clipboard manager
exec-once = ~/.config/hypr/scripts/battery-notify.sh

# --- AUTOSTART RICE DASHBOARD --- #
exec-once = sleep 1 && kitty --class kitty-jam tty-clock -c -b -C 2
exec-once = sleep 1.5 && kitty --class kitty-nvim nvim
exec-once = sleep 2 && kitty --class kitty-bawah
